language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"

env:
    - PIP_USE_MIRRORS=true

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install ."

# command to run tests
script: "py.test tests"